affordances:
  version: '1.0'
  affordances:
  - name: BENCH
    interaction_type: instant
    costs: {}
    opening_hours:
      enabled: false
    deployment:
      type: fixed
      positions:
      - - 4
        - 4
    interactions:
      on_start: []
      per_tick: []
      on_completion: []
      on_early_exit: []
      on_failure: []
  modulations: []
