"""Variable & Feature System (VFS) module.

The VFS provides a declarative way to define variables, observations, and
action effects for the Townlet environment.

Phase 1: Schema definitions, registry, observation specs
Phase 2: Derivation graphs, complex types, expression evaluation
"""

from townlet.vfs import vtc_kernels
from townlet.vfs.communication import canonical_l6_message_variables
from townlet.vfs.dynamic_needs import canonical_fixed_slot_dynamic_need_variables
from townlet.vfs.generalisation import (
    VFSGeneralisationPack,
    VFSGeneralisationReport,
    VFSGeneralisationSignature,
    assert_held_out_generalisation_split,
    build_vfs_generalisation_signature,
    operator_grammar_signature,
)
from townlet.vfs.registry import DynamicVariableMutation, VariableRegistry, VFSRegistryProtocol
from townlet.vfs.relational import canonical_l5_relational_variables
from townlet.vfs.schema import (
    NormalizationSpec,
    VariableDef,
    WriteSpec,
)
from townlet.vfs.schema_hashes import (
    canonical_action_schema,
    canonical_transition_graph_schema,
    canonical_variable_schema,
    compute_action_schema_hash,
    compute_transition_graph_hash,
    compute_variable_schema_hash,
    compute_vfs_hash,
)
from townlet.vfs.transition_graph import DEFAULT_TRANSITION_PHASES, TransitionPhaseGraph
from townlet.vfs.vtc import (
    CompiledVTCActionWrite,
    CompiledVTCAffordanceGate,
    CompiledVTCInteractionCompletionBonus,
    CompiledVTCInteractionProgress,
    CompiledVTCModulation,
    CompiledVTCPassiveDepletion,
    CompiledVTCRewardComponent,
    CompiledVTCSocialResidueRule,
    CompiledVTCTerminalCondition,
    CompiledVTCThresholdCascade,
    VTCActionWriteProgram,
    VTCActionWriteSource,
    VTCAffordanceGateProgram,
    VTCAffordanceGateSource,
    VTCInteractionProgressProgram,
    VTCInteractionProgressResult,
    VTCInteractionProgressSource,
    VTCModulationProgram,
    VTCModulationSource,
    VTCPassiveDepletionProgram,
    VTCPassiveDepletionSource,
    VTCRewardConfigSource,
    VTCRewardProgram,
    VTCSocialResidueProgram,
    VTCSocialResidueSource,
    VTCTerminalConditionProgram,
    VTCTerminalConditionSource,
    VTCThresholdCascadeProgram,
    VTCThresholdCascadeSource,
    compile_vtc_action_writes,
    compile_vtc_action_writes_with_phase_graph,
    compile_vtc_affordance_gates,
    compile_vtc_affordance_gates_with_phase_graph,
    compile_vtc_affordance_occupancy,
    compile_vtc_affordance_occupancy_with_phase_graph,
    compile_vtc_interaction_progress,
    compile_vtc_interaction_progress_with_phase_graph,
    compile_vtc_modulations,
    compile_vtc_modulations_with_phase_graph,
    compile_vtc_passive_depletions,
    compile_vtc_passive_depletions_with_phase_graph,
    compile_vtc_reward_components,
    compile_vtc_reward_components_with_phase_graph,
    compile_vtc_social_residue_rules,
    compile_vtc_social_residue_rules_with_phase_graph,
    compile_vtc_terminal_conditions,
    compile_vtc_terminal_conditions_with_phase_graph,
    compile_vtc_threshold_cascades,
    compile_vtc_threshold_cascades_with_phase_graph,
)

__all__ = [
    "CompiledVTCActionWrite",
    "CompiledVTCAffordanceGate",
    "CompiledVTCInteractionCompletionBonus",
    "CompiledVTCInteractionProgress",
    "CompiledVTCModulation",
    "CompiledVTCPassiveDepletion",
    "CompiledVTCRewardComponent",
    "CompiledVTCSocialResidueRule",
    "CompiledVTCTerminalCondition",
    "CompiledVTCThresholdCascade",
    "DEFAULT_TRANSITION_PHASES",
    "DynamicVariableMutation",
    "NormalizationSpec",
    "VariableDef",
    "VariableRegistry",
    "TransitionPhaseGraph",
    "VTCActionWriteProgram",
    "VTCActionWriteSource",
    "VTCAffordanceGateProgram",
    "VTCAffordanceGateSource",
    "VTCInteractionProgressProgram",
    "VTCInteractionProgressResult",
    "VTCInteractionProgressSource",
    "VTCModulationProgram",
    "VTCModulationSource",
    "VTCPassiveDepletionProgram",
    "VTCPassiveDepletionSource",
    "VTCRewardConfigSource",
    "VTCRewardProgram",
    "VTCSocialResidueProgram",
    "VTCSocialResidueSource",
    "VTCTerminalConditionProgram",
    "VTCTerminalConditionSource",
    "VTCThresholdCascadeProgram",
    "VTCThresholdCascadeSource",
    "VFSRegistryProtocol",
    "VFSGeneralisationPack",
    "VFSGeneralisationReport",
    "VFSGeneralisationSignature",
    "WriteSpec",
    "assert_held_out_generalisation_split",
    "build_vfs_generalisation_signature",
    "canonical_fixed_slot_dynamic_need_variables",
    "canonical_l6_message_variables",
    "canonical_l5_relational_variables",
    "canonical_action_schema",
    "canonical_transition_graph_schema",
    "canonical_variable_schema",
    "compute_action_schema_hash",
    "compute_transition_graph_hash",
    "compute_variable_schema_hash",
    "compute_vfs_hash",
    "operator_grammar_signature",
    "compile_vtc_action_writes",
    "compile_vtc_action_writes_with_phase_graph",
    "compile_vtc_affordance_occupancy",
    "compile_vtc_affordance_occupancy_with_phase_graph",
    "compile_vtc_affordance_gates",
    "compile_vtc_affordance_gates_with_phase_graph",
    "compile_vtc_interaction_progress",
    "compile_vtc_interaction_progress_with_phase_graph",
    "compile_vtc_modulations",
    "compile_vtc_modulations_with_phase_graph",
    "compile_vtc_passive_depletions",
    "compile_vtc_passive_depletions_with_phase_graph",
    "compile_vtc_reward_components",
    "compile_vtc_reward_components_with_phase_graph",
    "compile_vtc_social_residue_rules",
    "compile_vtc_social_residue_rules_with_phase_graph",
    "compile_vtc_terminal_conditions",
    "compile_vtc_terminal_conditions_with_phase_graph",
    "compile_vtc_threshold_cascades",
    "compile_vtc_threshold_cascades_with_phase_graph",
    "vtc_kernels",
]
