"""Variable & Feature System (VFS) module.

The VFS provides a declarative way to define variables, observations, and
action effects for the Townlet environment.

Phase 1: Schema definitions, registry, observation specs
Phase 2: Derivation graphs, complex types, expression evaluation
"""

from townlet.vfs.observation_builder import VFSObservationSpec, apply_normalization
from townlet.vfs.registry import VariableRegistry, VFSRegistryProtocol
from townlet.vfs.schema import (
    NormalizationSpec,
    ObservationField,
    VariableDef,
    WriteSpec,
)
from townlet.vfs.schema_hashes import (
    canonical_action_schema,
    canonical_observation_schema,
    canonical_transition_graph_schema,
    canonical_variable_schema,
    compute_action_schema_hash,
    compute_observation_schema_hash,
    compute_transition_graph_hash,
    compute_variable_schema_hash,
    compute_vfs_hash,
)
from townlet.vfs.transition_graph import DEFAULT_TRANSITION_PHASES, TransitionPhaseGraph
from townlet.vfs.vtc import (
    CompiledVTCActionWrite,
    CompiledVTCAffordanceGate,
    CompiledVTCInteractionCompletionBonus,
    CompiledVTCInteractionProgress,
    CompiledVTCModulation,
    CompiledVTCPassiveDepletion,
    CompiledVTCTerminalCondition,
    CompiledVTCThresholdCascade,
    VTCActionWriteProgram,
    VTCActionWriteSource,
    VTCAffordanceGateProgram,
    VTCAffordanceGateSource,
    VTCInteractionProgressProgram,
    VTCInteractionProgressResult,
    VTCInteractionProgressSource,
    VTCModulationProgram,
    VTCModulationSource,
    VTCPassiveDepletionProgram,
    VTCPassiveDepletionSource,
    VTCTerminalConditionProgram,
    VTCTerminalConditionSource,
    VTCThresholdCascadeProgram,
    VTCThresholdCascadeSource,
    compile_vtc_action_writes,
    compile_vtc_action_writes_with_phase_graph,
    compile_vtc_affordance_gates,
    compile_vtc_affordance_gates_with_phase_graph,
    compile_vtc_interaction_progress,
    compile_vtc_interaction_progress_with_phase_graph,
    compile_vtc_modulations,
    compile_vtc_modulations_with_phase_graph,
    compile_vtc_passive_depletions,
    compile_vtc_passive_depletions_with_phase_graph,
    compile_vtc_terminal_conditions,
    compile_vtc_terminal_conditions_with_phase_graph,
    compile_vtc_threshold_cascades,
    compile_vtc_threshold_cascades_with_phase_graph,
)

__all__ = [
    "CompiledVTCActionWrite",
    "CompiledVTCAffordanceGate",
    "CompiledVTCInteractionCompletionBonus",
    "CompiledVTCInteractionProgress",
    "CompiledVTCModulation",
    "CompiledVTCPassiveDepletion",
    "CompiledVTCTerminalCondition",
    "CompiledVTCThresholdCascade",
    "DEFAULT_TRANSITION_PHASES",
    "NormalizationSpec",
    "ObservationField",
    "VariableDef",
    "VariableRegistry",
    "TransitionPhaseGraph",
    "VTCActionWriteProgram",
    "VTCActionWriteSource",
    "VTCAffordanceGateProgram",
    "VTCAffordanceGateSource",
    "VTCInteractionProgressProgram",
    "VTCInteractionProgressResult",
    "VTCInteractionProgressSource",
    "VTCModulationProgram",
    "VTCModulationSource",
    "VTCPassiveDepletionProgram",
    "VTCPassiveDepletionSource",
    "VTCTerminalConditionProgram",
    "VTCTerminalConditionSource",
    "VTCThresholdCascadeProgram",
    "VTCThresholdCascadeSource",
    "VFSRegistryProtocol",
    "VFSObservationSpec",
    "WriteSpec",
    "apply_normalization",
    "canonical_action_schema",
    "canonical_observation_schema",
    "canonical_transition_graph_schema",
    "canonical_variable_schema",
    "compute_action_schema_hash",
    "compute_observation_schema_hash",
    "compute_transition_graph_hash",
    "compute_variable_schema_hash",
    "compute_vfs_hash",
    "compile_vtc_action_writes",
    "compile_vtc_action_writes_with_phase_graph",
    "compile_vtc_affordance_gates",
    "compile_vtc_affordance_gates_with_phase_graph",
    "compile_vtc_interaction_progress",
    "compile_vtc_interaction_progress_with_phase_graph",
    "compile_vtc_modulations",
    "compile_vtc_modulations_with_phase_graph",
    "compile_vtc_passive_depletions",
    "compile_vtc_passive_depletions_with_phase_graph",
    "compile_vtc_terminal_conditions",
    "compile_vtc_terminal_conditions_with_phase_graph",
    "compile_vtc_threshold_cascades",
    "compile_vtc_threshold_cascades_with_phase_graph",
]
