"""Registry of universe-compiler diagnostic codes.

Every ``CompilationMessage.code`` the compiler emits is declared here, grouped
by the pipeline stage that raises it (see ``stages.CompilationStage``). Raise
sites cite registry members, never string literals — the registry is what makes
diagnostics triage-able and greppable in one place.
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    """Closed vocabulary of compiler diagnostic codes."""

    # --- Stage 0: preflight (scoping, filesystem, YAML syntax) ---
    SCOPING_LEVEL_DIRECTORY = "SCOPING_LEVEL_DIRECTORY"
    SCOPING_MISSING_EXPERIMENT_FILE = "SCOPING_MISSING_EXPERIMENT_FILE"
    SCOPING_FORBIDDEN_LEVEL_FILE = "SCOPING_FORBIDDEN_LEVEL_FILE"
    MISSING_FILE = "MISSING_FILE"
    MISSING_LEVELS_DIR = "MISSING_LEVELS_DIR"
    YAML_SYNTAX_ERROR = "YAML_SYNTAX_ERROR"

    # --- Stage 1: parse ---
    LOAD_ERROR = "LOAD_ERROR"
    LEVEL_LOAD_ERROR = "LEVEL_LOAD_ERROR"
    NO_CURRICULUM_LEVELS = "NO_CURRICULUM_LEVELS"

    # --- Stage 2: safety limits ---
    CONFIG_LIMIT_EXCEEDED = "CONFIG_LIMIT_EXCEEDED"
    ITEM_TYPES_LIMIT_EXCEEDED = "ITEM_TYPES_LIMIT_EXCEEDED"
    GRID_SIZE_LIMIT_EXCEEDED = "GRID_SIZE_LIMIT_EXCEEDED"
    SPAWN_RULE_LIMIT_EXCEEDED = "SPAWN_RULE_LIMIT_EXCEEDED"

    # --- Stage 3: cross-validate semantics ---
    TEMPORAL_DAY_LENGTH_MISSING = "TEMPORAL_DAY_LENGTH_MISSING"
    MULTI_TICK_REQUIRES_TEMPORAL = "MULTI_TICK_REQUIRES_TEMPORAL"
    VISION_INCOMPATIBLE = "VISION_INCOMPATIBLE"
    SUBSTRATE_ACTION_INCOMPATIBLE = "SUBSTRATE_ACTION_INCOMPATIBLE"
    SUBSTRATE_ACTION_WARNING_AS_ERROR = "SUBSTRATE_ACTION_WARNING_AS_ERROR"
    INTERACTION_RADIUS_MISSING = "INTERACTION_RADIUS_MISSING"
    MODULATION_INVALID_REFERENCE = "MODULATION_INVALID_REFERENCE"
    CASCADE_INVALID_METER = "CASCADE_INVALID_METER"
    CASCADE_CYCLE = "CASCADE_CYCLE"
    METER_VOCAB_MISMATCH = "METER_VOCAB_MISMATCH"
    AFFORDANCE_VOCAB_MISMATCH = "AFFORDANCE_VOCAB_MISMATCH"
    CASCADE_MISSING = "CASCADE_MISSING"
    CASCADE_EXTRA = "CASCADE_EXTRA"
    MODULATION_MISSING = "MODULATION_MISSING"
    MODULATION_EXTRA = "MODULATION_EXTRA"
    AFFORDANCE_OPENING_HOURS_MISSING = "AFFORDANCE_OPENING_HOURS_MISSING"
    AFFORDANCE_DEPLOYMENT_POSITIONS_MISSING = "AFFORDANCE_DEPLOYMENT_POSITIONS_MISSING"
    AFFORDANCE_INVALID_METER = "AFFORDANCE_INVALID_METER"
    ENABLED_AFFORDANCES_INVALID = "ENABLED_AFFORDANCES_INVALID"
    GRID_CAPACITY_EXCEEDED = "GRID_CAPACITY_EXCEEDED"
    LEVEL_DRIVE_MISSING = "LEVEL_DRIVE_MISSING"
    LEVEL_DRIVE_EXTRINSIC_MISSING = "LEVEL_DRIVE_EXTRINSIC_MISSING"
    LEVEL_DRIVE_INTRINSIC_MISSING = "LEVEL_DRIVE_INTRINSIC_MISSING"

    # --- Stage 5: resolve references ---
    UAC_RES_CASCADE = "UAC-RES-CASCADE"
    UAC_RES_VFS = "UAC-RES-VFS"
    UAC_RES_ITEM = "UAC-RES-ITEM"
    DAC_REF_UNDEFINED_MODIFIER_BAR = "DAC-REF-001"
    DAC_REF_UNDEFINED_MODIFIER_VARIABLE = "DAC-REF-002"
    DAC_REF_UNDEFINED_EXTRINSIC_BAR = "DAC-REF-003"
    DAC_REF_UNDEFINED_BAR_BONUS_BAR = "DAC-REF-004"
    DAC_REF_UNDEFINED_VARIABLE_BONUS = "DAC-REF-005"
    DAC_REF_UNDEFINED_APPROACH_AFFORDANCE = "DAC-REF-006"
    DAC_REF_UNDEFINED_COMPLETION_AFFORDANCE = "DAC-REF-007"
    DAC_REF_UNDEFINED_STREAK_AFFORDANCE = "DAC-REF-008"
    DAC_REF_UNDEFINED_TIMING_AFFORDANCE = "DAC-REF-009"
    DAC_REF_UNDEFINED_EFFICIENCY_BAR = "DAC-REF-010"
    DAC_REF_UNDEFINED_CRISIS_BAR = "DAC-REF-011"
    DAC_REF_UNDEFINED_ECONOMIC_BAR = "DAC-REF-012"
    DAC_REF_UNDEFINED_BALANCE_BAR = "DAC-REF-013"
    DAC_REF_UNDEFINED_ACHIEVEMENT_BAR = "DAC-REF-014"
    DAC_REF_UNDEFINED_VFS_VARIABLE = "DAC-REF-015"

    # --- Stages 6-7: shared artifacts and per-level compile ---
    VFS_PROFILE_COMPILE = "VFS-PROFILE-COMPILE"
    VFS_LEVEL_COMPILE = "VFS-LEVEL-COMPILE"
    UAC_OPT_CASCADE = "UAC-OPT-CASCADE"
    UAC_OPT_MODULATION = "UAC-OPT-MODULATION"
    UAC_META_DAY_LENGTH = "UAC-META-DAY-LENGTH"
    UAC_META_VERSION = "UAC-META-VERSION"
