environment:
  version: "1.0"
  meters:
    - name: energy
      description: "Energy"
      range_type:
        kind: minmax
        clip: true
    - name: health
      description: "Health"
      range_type:
        kind: minmax
        clip: true
    - name: money
      description: "Cash"
      range_type:
        kind: minmax
        clip: true
  affordances:
    - name: Bed
      description: "Rest"
      category: rest
  cascade_graph: []
  modulation_graph: []
  variables: []
  cues: []
