affordances:
  version: "1.0"
  affordances:
    - name: SLEEP
      interaction_type: instant
      costs:
        energy: 0.0
      opening_hours:
        enabled: false
      deployment:
        type: fixed
        positions:
          - - 0
            - 0
          - - 7
            - 7
      interactions:
        on_start:
          - modify: target.bar.energy
            value: target.bar.energy + 0.8
        per_tick: []
        on_completion: []
        on_early_exit: []
        on_failure: []
    - name: DOCTOR
      interaction_type: instant
      costs:
        energy: 0.0
      opening_hours:
        enabled: false
      deployment:
        type: fixed
        positions:
          - - 0
            - 7
          - - 7
            - 0
      interactions:
        on_start:
          - modify: target.bar.health
            value: target.bar.health + 0.8
        per_tick: []
        on_completion: []
        on_early_exit: []
        on_failure: []
  modulations: []
